### ISSUE TITLE
카테고리 도메인 리팩토링 - 패키지 위치, 도메인 로직, 쿼리 개선

### ISSUE THREAD

**Issue by le2sky** [YAPP-Github/21st-ALL-Rounder-Team-2-BE#155]
카테고리와 관련된 코드들을 개선합니다. 현재 refactor/155 브랜치에서 진행 내용 볼 수 있습니다!

## 작업 내용
- category_limit_count를 클래스 상수로 변경
- category_shuffle 테스트 개선
- repository 패키지 위치 개선
- 리포지터리 위치 개선에 의한 docs 업데이트
- 카테고리 도메인 규칙, 로직 개선
- 카테고리 네이밍 제약 강화(최대 20글자)
- shuffle 매개변수 중 changeCategorySequenceDtos → changedCategories로 네이밍 개선(기존에 xxDtos로 설정되어 있었음)
- shuffle 로직 도메인 서비스로 이동

### 응용 서비스에서 자주 보이는 패턴

```java

    // id를 이용해서 카테고리를 가져와라
    Category category = Optional.ofNullable(categoryRepository.findCategoryEntityGraphById(id))
        .orElseThrow(CategoryNotFoundException::new);

    // 사용자를 찾아와라
    UserJpaEntity user = findUser(userId);

    // 조회된 카테고리가 로그인한 사용자의 카테고리인가? 
    validateOwnedByUser(category, user);
```

개선할 수 있다면?

```java
select * from category where category_id = ? and user_id = ?
```

⇒ 성능 차이는 별로 안나겠지만. 응용 영역 코드 복잡도 낮출 수 있어요! @akalswl14 의견 궁금합니다!

```java
return categoryRepository.findCategoryEntityGraphById(id)
        .orElseThrow(CategoryNotFoundException::new);
```

### 테스트 코드에서 auto_increment

- 현재 카테고리에서는 실패하는 테스트 코드가 없도록 개선
- 대표적으로 shuffle 테스트가 auto_increment 때문에 실패하고 있었음
    - 현재 임시 방편으로 auto_increment된 id 값을 추적하는 변수를 생성해서 then 절에 넣어줌
- auto_increment에 영향을 받지 않는 테스트 코드를 지향하자
    - 티피타피는 어떻게 극복하고 있는지?

**Comment by akalswl14** [comment]
@le2sky 
저는 쿼리의 양이 비록 1개지만, db와의 네트워크 분기를 하나 줄인 것이기 때문에 미약하지만 성능상으로도 유의미하다고 생각됩니다 !
말씀 해주신것처럼 개선해도 좋을 것 같습니다 :D
