### ISSUE TITLE
아키텍처 디자인 개선 제안

### ISSUE THREAD

**Issue by le2sky** [YAPP-Github/21st-ALL-Rounder-Team-2-BE#24]
더 좋은 아키텍처를 위한 고민을 담은 글을 공유 드립니다!

> 더 좋은 의견이나 방향 있다면 자유롭게 댓글 남겨주세요!

- [늘로그 - 아르티 아키텍처 디자인에 대해서 끄적](https://le2ksy.tistory.com/72)

**Comment by le2sky** [comment]
@akalswl14 
현재 패키지 구조가 
- dto
- exception
- domain
 
...등등이 존재하는데 `archive.domain` 은 category, exhibit.. 등으로 패키징 되어 있지만,
`archive.exception` 같은 경우에는 패키징이 안 되어 있어요. 어떤 기준으로 패키징하는게 좋을까요?

일단 당장 제가 시도해보고 싶은 건, 아래 도메인 객체들에 대해서 패키지를 세분화 시키지 않고 통합하는 겁니다.(내부 패키징 제거) 심각한 이유는 아니지만, 패키징되어 있으면 별개 영역의 것들로 생각되기 때문입니다! 좋은 의견 있으면 피드백 부탁드려요

![image](https://user-images.githubusercontent.com/39932141/215344810-35702a2a-a232-4b5b-bb93-8426efc73af6.png)

**Comment by akalswl14** [comment]
현재 전시 Service, Controller에는 비슷하지만 다른 객체를 반환해 각 메소드 명이 매우 유사합니다. 이름이 유사해서, 이름만으로 메소드의 역할을 알기가 매우 어렵습니다. 
아키텍처를 개선할 때에, 비슷한 객체를 반환하는 메소드를 고려하여 재정의 / 재분류 하면 좋을 것 같습니다.

**Comment by le2sky** [comment]
@akalswl14 헉 이제 봤네요 좋은 의견 감사합니다 ㅎㅎㅎ

**Comment by le2sky** [comment]
방향성 잡힌 것 같아서 이슈 닫겠습니다!
