### ISSUE TITLE
마이 페이지 공지사항 기능 구현

### ISSUE THREAD

**Issue by le2sky** [YAPP-Github/21st-ALL-Rounder-Team-2-BE#36]
공지사항이 생성됐을 경우 모든 사용자에게 알림이 간다면 알림 서버를 연동할 수 있는 가장 쉬운 기회로 보입니다.
기능 자체는 쉽지만,  알림 서버 연동이나 어드민 페이지까지 고려한다면 노력이 많이 필요합니다. 회의록 봤는데, 우선 순위도 나중으로 잡혀있는데, 일단 이슈는 발행해 놓을게요!

- [ ] 공지사항에 대한 어드민 페이지 필요성 생각 해보기
- [ ] 알림 서버 연동 필요성 생각 해보기

**Comment by akalswl14** [comment]
마이페이지 관련 API
- [ ] 마이페이지 썸네일 조회
