### ISSUE TITLE
기본 카테고리 로직 제거

### ISSUE THREAD

**Issue by le2sky** [YAPP-Github/21st-ALL-Rounder-Team-2-BE#52]
기본 카테고리가 있다기 보단, 전체 기록으로 보는게 맞음.

- [x] 시퀀스 변경 로직 수정
- [x] 기본 카테고리 유효성 검사 로직 제거
- [x] 관련 클래스 제거
- [x] 전체 기록 조회 로직 구현

**Comment by akalswl14** [comment]
요거는 어디 브랜치파서 작업하신걸까요 ?!

**Comment by le2sky** [comment]
feature/52인데 아직 반영을 안해놨어요! 오늘 새벽에 조금 테스트해보고 rebase한다음에 반영해둘게요!

**Comment by akalswl14** [comment]
아하 알겠습니당 혹시 메인 브랜치 머지될때 같이 반영되는 부분인지 확인차 여쭤봤습니다 천천히 하세요~~~~~~~!!
