### ISSUE TITLE
컨트롤러 테스트, 유닛 테스트 추가 및 Mockito 적용

### ISSUE THREAD

**Issue by akalswl14** [YAPP-Github/21st-ALL-Rounder-Team-2-BE#86]
보다 안정적인 API 수행을 위하여, 테스트 구조 개선을 통한 유닛 테스트화와 함께 컨트롤러 테스트 추가가 필요합니다.
또한, 테스트 객체를 모킹하여 보다 자세한 테스트 시나리오를 갖춘 테스트를 구성하면 좋을 것 같습니다.

**Comment by le2sky** [comment]
좋은 의견 감사합니다! 중요한 이슈라고 생각이 들어 고정해둘게요!

**Comment by le2sky** [comment]
https://github.com/YAPP-Github/21st-ALL-Rounder-Team-2-BE/pull/106

위 PR에서 테스트 관련 이야기 언급해서 첨부해두겠습니다!

**Comment by le2sky** [comment]
방향성 잡힌 것 같아서 이슈 닫겠습니다!
